const phone='8801713521643';
const products=[
 ['Oil & Gas Steam Boilers','Automatic, efficient and reliable','https://taiguo-boiler.com/upload/portal/20251029/5bf079c24a94553a4777cb33b50911cd.png'],
 ['Biomass Steam Boilers','Multi-fuel industrial steam systems','https://taiguo-boiler.com/upload/portal/20251029/cfb7fddb67c1d424510384ababc41285.png'],
 ['Electric Boilers','Clean, compact and precisely controlled','https://taiguo-boiler.com/upload/portal/20251029/c434df4e662e2e13ca78e37331d60859.png'],
 ['Thermal Oil Heaters','High temperature at low pressure','https://taiguo-boiler.com/upload/portal/20251029/d3f8f019a4bee58da79e537b5f5d9b0f.png'],
 ['Hot Air Furnaces','Direct industrial process heating','https://taiguo-boiler.com/upload/portal/20251030/9e9d020a4624d922d9658f114ab37dfc.png'],
 ['Parts & Auxiliaries','Burners, controls, valves and pumps','https://taiguo-boiler.com/static/index/images/about.jpg']
];
const projects=[
 'https://taiguo-boiler.com/upload/admin/20251201/03941dd5b208647037cfb993975e0d11.jpg',
 'https://taiguo-boiler.com/upload/admin/20251201/cabb7a43976b97430ad97ac145bd6a15.jpg',
 'https://taiguo-boiler.com/upload/admin/20250908/28f1d74cdbc458c7c6aeb43033fe0795.jpg',
 'https://taiguo-boiler.com/upload/admin/20251201/9cb77030b9d2a752690e32cc5f5bf6b6.jpg'
];
function Logo(){return <div className="logo"><svg viewBox="0 0 120 90"><path d="M18 72C8 53 16 23 47 6c-7 17-8 34 3 47C38 67 28 73 18 72Z" fill="#e42528"/><path d="M101 14c9 20 2 49-32 70 8-17 8-34-2-46 12-15 23-24 34-24Z" fill="#ffd21c"/><path d="M45 57c12 10 26 8 42-7-8 17-22 29-38 31-14 1-24-6-31-18 9 4 18 2 27-6Z" fill="#e42528"/><path d="M74 32c-13-9-27-6-42 9 8-18 22-29 38-31 14-1 25 6 31 18-9-4-18-3-27 4Z" fill="#ffd21c"/></svg><span><b>TGGL</b><small>TAIGUO BOILER · BANGLADESH</small></span></div>}
function Arrow(){return <span aria-hidden="true">→</span>}
export default function Page(){return <>
 <div className="top"><div className="wrap"><span>Bangladesh Regional Sales Office</span><div><a href="tel:+8801713521643">+880 1713-521643</a><a href="mailto:taiguo-sobuj@4stex.com">taiguo-sobuj@4stex.com</a></div></div></div>
 <header><div className="wrap nav"><a href="#home"><Logo/></a><nav><a href="#products">Products</a><a href="#projects">Projects</a><a href="#about">About</a><a href="#contact">Contact</a></nav><a className="btn small" href={`https://wa.me/${phone}`} target="_blank">Get a quote</a></div></header>
 <main>
  <section className="hero" id="home"><div className="shade"/><div className="wrap heroGrid"><div className="heroCopy"><p className="eyebrow">INDUSTRIAL BOILER SYSTEMS FOR BANGLADESH</p><h1>Reliable heat.<br/><em>Engineered for industry.</em></h1><p className="lead">Steam boilers, biomass systems, electric boilers, thermal oil heaters and complete boiler-room solutions with dedicated Bangladesh sales support.</p><div className="actions"><a className="btn" href="#contact">Request quotation <Arrow/></a><a className="btn ghost" href="#products">Explore products</a></div><div className="stats"><div><b>Since 1976</b><span>Manufacturing experience</span></div><div><b>80+ countries</b><span>Global export reach</span></div><div><b>Local support</b><span>Gazipur, Bangladesh</span></div></div></div><aside><span className="tag">BANGLADESH OFFICE</span><div className="avatar">SU</div><h2>MD Sobuj Uddin</h2><p>Country Proprietor<br/><strong>Manager, Sales &amp; Marketing (Bangladesh)</strong></p><a href="tel:+8801713521643">+880 1713-521643</a><a href="mailto:taiguo-sobuj@4stex.com">taiguo-sobuj@4stex.com</a><div className="social"><a href={`https://wa.me/${phone}`} target="_blank">WhatsApp</a><span>WeChat: +8801713521643</span></div></aside></div></section>
  <section className="intro"><div className="wrap twoCol"><div><p className="eyebrow red">PRODUCT PORTFOLIO</p><h2>Industrial heating solutions matched to your process.</h2></div><p>From capacity selection and fuel choice to quotation, delivery communication and project follow-up, the Bangladesh office provides a direct local point of contact.</p></div></section>
  <section className="products" id="products"><div className="wrap cards">{products.map((p,i)=><article className="card" key={p[0]}><div className="media"><span>{String(i+1).padStart(2,'0')}</span><img src={p[2]} alt={p[0]}/></div><div className="body"><small>{p[1]}</small><h3>{p[0]}</h3><p>Industrial-grade equipment configured around capacity, pressure, fuel and process requirements.</p><a href="#contact">Request specifications <Arrow/></a></div></article>)}</div></section>
  <section className="process"><div className="wrap"><div className="title"><p className="eyebrow red">PROJECT WORKFLOW</p><h2>From requirement to commissioning.</h2></div><div className="steps"><article><b>01</b><h3>Requirement review</h3><p>Capacity, pressure, fuel, application and site conditions.</p></article><article><b>02</b><h3>Technical selection</h3><p>Suitable boiler type, auxiliaries and control configuration.</p></article><article><b>03</b><h3>Commercial quotation</h3><p>Clear equipment scope, lead time and delivery coordination.</p></article><article><b>04</b><h3>Project follow-up</h3><p>Local communication through installation and after-sales stages.</p></article></div></div></section>
  <section className="work" id="projects"><div className="wrap"><div className="workHead"><div><p className="eyebrow">PROJECTS &amp; MANUFACTURING</p><h2>Built for demanding industrial environments.</h2></div><p>Industrial boiler manufacturing, shipment and installation references from Taiguo projects.</p></div><div className="gallery">{projects.map((x,i)=><figure className={`g${i+1}`} key={x}><img src={x} alt="Taiguo industrial boiler project"/><figcaption>{['Boiler manufacturing','Industrial installation','Global shipment','Production facility'][i]}</figcaption></figure>)}</div></div></section>
  <section className="about" id="about"><div className="wrap aboutGrid"><div><p className="eyebrow">ABOUT TAIGUO</p><h2>Industrial boiler engineering with global reach.</h2><p>Henan Taiguo Boiler Products Co., Ltd. manufactures industrial boilers and process-heating equipment for projects across international markets. The Bangladesh office connects local buyers with the manufacturer for product selection, quotations and project communication.</p><div className="chips"><span>ISO 9001</span><span>ASME</span><span>CE</span><span>Grade A Boilers</span></div></div><div className="numbers"><div><b>1976</b><span>Founded</span></div><div><b>60,000㎡</b><span>Factory area</span></div><div><b>80+</b><span>Export countries</span></div><div><b>8</b><span>Quality systems</span></div></div></div></section>
  <section className="contact" id="contact"><div className="wrap contactGrid"><div><p className="eyebrow red">CONTACT BANGLADESH</p><h2>Discuss your boiler requirement.</h2><p>Send the intended application, required capacity, pressure, fuel type and installation location for an initial product recommendation.</p><div className="person"><div className="avatar">SU</div><div><b>MD Sobuj Uddin</b><span>Country Proprietor · Manager, Sales &amp; Marketing</span></div></div></div><div className="panel"><div><small>PHONE · WHATSAPP · WECHAT</small><a href="tel:+8801713521643">+880 1713-521643</a></div><div><small>EMAIL</small><a href="mailto:taiguo-sobuj@4stex.com">taiguo-sobuj@4stex.com</a></div><div><small>BANGLADESH OFFICE</small><p>Rajendrapur Bazar, Sreepur, Gazipur, Dhaka, Bangladesh</p></div><div><small>HEAD OFFICE</small><p>Zhangji Industrial Park, adjacent to National Highway 311, Taikang County, Zhoukou, Henan, China</p></div><a className="btn full" href={`https://wa.me/${phone}?text=Hello%20Mr.%20Sobuj%2C%20I%20would%20like%20a%20Taiguo%20Boiler%20quotation.`} target="_blank">Start WhatsApp enquiry <Arrow/></a></div></div></section>
 </main>
 <footer><div className="wrap foot"><div><Logo/><p>Taiguo industrial boiler solutions with regional sales support for Bangladesh.</p></div><div><h3>Products</h3><a href="#products">Steam Boilers</a><a href="#products">Biomass Boilers</a><a href="#products">Thermal Oil Heaters</a></div><div><h3>Contact</h3><a href="tel:+8801713521643">+880 1713-521643</a><a href="mailto:taiguo-sobuj@4stex.com">Email Bangladesh Office</a></div></div><div className="wrap copy"><span>© 2026 Taiguo Boiler Bangladesh</span><span>Regional sales website</span></div></footer>
 <a className="float" href={`https://wa.me/${phone}`} target="_blank" aria-label="WhatsApp">WA</a>
 </>}